version: '3.7'

services: 
  webapp:
    build: 
      context: .
      dockerfile: src/Webapp/Dockerfile

  webapi:
    build: 
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets