version: '3.7'

services: 
  webapp:
    image: "${DOCKER_REGISTRY:-awoaoa}/samples/webapp:${VERSION:-latest}"
    ports: 
      - 80:80
    links: 
      - "webapi:api.svr"
    depends_on: 
      - webapi

  webapi:
    image: "${DOCKER_REGISTRY:-awoaoa}/samples/webapi:${VERSION:-latest}"